### ISSUE TITLE
relative path is not working

### ISSUE THREAD

**Issue by geyang** [jstransformers/jstransformer-scss#7]
This one is very annoying. I am using jstransformer-scss via jade as a jade filter.

When doing: 

``` jade

include:scss "path/to/scss/file"
```

if there is any import inside the scss file, the import path is relative to the jade file, which is a huge headache since the import directive should be relative to the scss file itself.

**Comment by RobLoach** [comment]
Can you add the base to your `include-path`?

**Comment by ForbesLindesay** [comment]
This is because jade@1 is still calling `jstransformer.render` rather than `jstransformer.renderFile`.  This will be fixed by the release of jade@2.0.0
